# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdeb5f559af870f8684842da2f0b42efb41fc3b670ff23fc5cd8efa95fc4fd07d7fe499d69f7a36f9d5f27d6386779dec4ea07cb88701b8c5c37867f12fadf22

test:
  secret_key_base: 40a5682045846af193b469284d086354de90a222fc8f667e2c8b6cfe62d7f47513404b8e135cb546d81f74f8cb8ff51d036c8f2b45455b594c93c7cfd53df177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
